routes/web.php
<?php

// Route::get('/', function () {
//     return view('index');
// });
route::get('/','testController@home');
route::get('about','testController@about');

Route::group(['namespace'=>'Admin'],function (){
    Route::get('auth/login','AuthController@showLoginForm')->name('auth.showloginform');
    Route::post('/','AuthController@login')->name('login');
    Route::get('logout','AuthController@logout')->name('logout');
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'is_admin',
    'prefix'        => 'dashboard'
],function (){
    Route::name('dash.')->group(function (){
        Route::get('','DashboardController@index')->name('index');
    });
});

Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'is_admin',
'prefix'        => 'item'
],function (){
    Route::name('item.')->group(function (){
        Route::get('','ItemController@index')->name('index');
        Route::get('{id}','ItemController@show')->name('show');
        Route::post('','ItemController@store')->name('store');
        Route::get('edit/{id}','ItemController@edit')->name('edit');
        Route::put('{id}','ItemController@update')->name('update');
        Route::delete('{id}','ItemController@delete')->name('delete');
        Route::post('item/import_excel', 'ItemController@import_excel');
    });
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'supplier'
],function (){
    Route::name('supplier.')->group(function (){
        Route::get('','SupplierController@index')->name('index');
        Route::post('','SupplierController@store')->name('store');
        Route::get('edit/{id}','SupplierController@edit')->name('edit');
        Route::put('{id}','SupplierController@update')->name('update');
        Route::delete('{id}','SupplierController@destroy')->name('delete');
    });
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'category'
],function (){
    Route::name('category.')->group(function (){
        Route::get('','CategoryItemController@index')->name('index');
        Route::post('','CategoryItemController@store')->name('store');
        Route::get('edit/{id}','CategoryItemController@edit')->name('edit');
        Route::put('{id}','CategoryItemController@update')->name('update');
        Route::delete('category.delete/{id}','CategoryItemController@delete')->name('delete');
    });
});

Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'admin'
],function (){
    Route::name('admin.')->group(function (){
        Route::get('','AdminController@index')->name('index');
        Route::post('','AdminController@store')->name('store');
        Route::get('edit/{id}','AdminController@edit')->name('edit');
        Route::put('{id}','AdminController@update')->name('update');
        Route::delete('category.delete/{id}','AdminController@delete')->name('delete');
    });
});


Route::get('beranda', function () {
    return view('index');
});
Route::get('transaksi', function () {
    return view('transaksi');
});


Route::get('website/{id}', 'Admin\BarangController@tampil')->name('kategori.show');
// Route::get('website/dasi', 'Admin\BarangController@tampil');
//
Route::get('website/kaos_kaki', 'Admin\BarangController@tampil_kaoskaki');

Route::get('website/topi', 'Admin\BarangController@tampil_topi');

Route::get('website/atribut_pramuka', 'Admin\BarangController@tampil_atributperamuka');

Route::get('website/sepatu', 'Admin\BarangController@tampil_sepatu');

Route::get('website/badge_jurusan', 'Admin\BarangController@tampil_badge');

Route::get('website/status', function () {
    return view('website/status');
});

// Route::get('/dashboard', 'DashboardController@index');

resources/views/about.blade.php
@extends('template')

@section('content')
<header class="main-header">
        <!-- Start Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light navbar-default bootsnav" style="background-color: #fffa78">
            <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                    <a class="navbar-brand" href="index.html"><img src="image/smeas11.png" class="logo" alt="" width="190"></a>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">
                        <li class="nav-item"><a class="nav-link" href="../">Beranda</a></li>

                        <li class="dropdown megamenu-fw">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Kategori</a>
                            <ul class="dropdown-menu megamenu-content" role="menu">
                                <li>
                                    <div class="row">
                                        <div class="col-menu col-md-3">
                                            <h6 class="title">Atribut</h6>
                                            <div class="content">
                                                <ul class="menu-col">
                                                    <li><a href=Bat Jurusan></a></li>
                                                    <li><a href="../website/badge_jurusan">Badge Jurusan</a></li>
                                                    <li><a href="../website/dasi">Dasi</a></li>
                                                    <li><a href="../website/kaos_kaki">Kaos Kaki</a></li>
                                                    <li><a href="../website/topi">Topi</a></li>
                                                    <li><a href="../website/atribut_pramuka">Atribut Pramuka</a></li>
                                                    <li><a href="../website/sepatu">Sepatu</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- end col-3 -->
                                        <div class="col-menu col-md-3">
                                            <h6 class="title">Alat Tulis</h6>
                                            <div class="content">
                                                <ul class="menu-col">
                                                    <li><a href="#">Pensil</a></li>
                                                    <li><a href="#">Penghapus</a></li>
                                                    <li><a href="#">Bolpoin</a></li>
                                                    <li><a href="#">Penggaris</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- end col-3 -->
                                        <div class="col-menu col-md-3">
                                            <h6 class="title">Makanan Ringan</h6>
                                            <div class="content">
                                                <ul class="menu-col">
                                                    <li><a href="shop.html">Bidaran</a></li>
                                                    <li><a href="shop.html">Makaroni</a></li>
                                                    <li><a href="shop.html">Krupuk</a></li>
                                                    <li><a href="shop.html"></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="col-menu col-md-3">
                                            <h6 class="title">Accessories</h6>
                                            <div class="content">
                                                <ul class="menu-col">
                                                    <li><a href="shop.html">Bags</a></li>
                                                    <li><a href="shop.html">Sunglasses</a></li>
                                                    <li><a href="shop.html">Fragrances</a></li>
                                                    <li><a href="shop.html">Wallets</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- end col-3 -->
                                    </div>
                                    <!-- end row -->
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="../about">Tentang Kami</a></li>
                        <!-- <li class="nav-item"><a class="nav-link" href="../website/status">Status Koperasi</a></li> -->
                       
                        
                        <!-- <li class="dropdown">
                            <a href="#" class="nav-link dropdown-toggle arrow" data-toggle="dropdown">SHOP</a>
                            <ul class="dropdown-menu">
                                <li><a href="cart.html">Cart</a></li>
                                <li><a href="checkout.html">Checkout</a></li>
                                <li><a href="my-account.html">My Account</a></li>
                                <li><a href="wishlist.html">Wishlist</a></li>
                                <li><a href="shop-detail.html">Shop Detail</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="service.html">Our Service</a></li> -->
                        <!-- <li class="nav-item"><a class="nav-link" href="kontak">Contact Us</a></li> -->
                    </ul>
                </div>
    </header>
<div class="all-title-box" style="background-image: url('template/images/smeascopy.jpg');">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>ABOUT US</h2>
                    <!-- <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul> -->
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start About Page  -->
    <div class="about-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2 class="noo-sh-title">SMEAS.Koperasi <span>By SMKN 1 Surabaya</span></h2>
                    <p>"Bingung mau kemana, Ya SMEAS Koperasi aja...."</p>
                    <p>SMEAS Koperasi adalah tefa yang dibuka oleh jurusan akutansi yang berguna untuk menyediakan barang-barang yang dibutuhkan oleh siswa.
                        </p>
                </div>
                <div class="col-lg-6">
                    <div class="banner-frame"> <img class="img-thumbnail img-fluid" src="template/images/smeascopy.jpg" alt="" />
                    </div>
                </div>
            </div>
            <!-- <div class="row my-5">
                <div class="col-sm-6 col-lg-4">
                    <div class="service-block-inner">
                        <h3>We are Trusted</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <div class="service-block-inner">
                        <h3>We are Professional</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <div class="service-block-inner">
                        <h3>We are Expert</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    </div> -->
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/atribut.blade.php
@extends('template')

@section('content')
<h4 style="margin-left: 20px;">
  <u>Atribut Sekolah
    </u>
      </h4>
            @foreach($tampilan as $atribut)          
        
        <div class="col-md-4">         
    <div class="polaroid">
    <a href="gallery/img/full/full1.png" title="Project Title" data-lightbox-gallery="gallery1"></a>
    <img width="150px" src="{{ asset('/data_file/'.$atribut->foto) }}" class="img-responsive" alt="Project Title" class="card-img-top" alt="..." height="200" width="200" style="margin-top: 10px;">
            <div class="container">
                <p><a href="batjurusan">{{$atribut->name}}</a></p>
                <p><a href="batjurusan">{{$atribut->stok}}</a></p>
                <p><a href="batjurusan">Rp.{{$atribut->price}}</a></p>
                
                @if($atribut->stok_barang == 0)
                <b style="color:red">Stok Habis </b>
                @else
                Stok ada{{$atribut->deskripsi}}
                @endif
            </div>
        </div>

    </div>
            @endforeach
<!-- ini div dari card-deck ya -->
      </div>
  </div>
</div>
</div>
  </div>

  

<style>
.polaroid {
  width: 250px;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  text-align: center;
}

.container {
  padding: 10px;
}
</style>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kategori.blade.php
@extends('admin.layouts.app')
@section('content-header')

    Data Siswa <br> <br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#create-student">
        <i class="fa fa-plus"></i> Tambah Kategori
    </button>
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#create-student">
            <i class="fa fa-plus"></i> Import Data Barang
        </button>
@endsection
@section('header-small')

@endsection
@section('content')
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Data Barang</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($data as $read)
                    <tr>
                        <td>{{$read->name}}</td>
                        <td>
                            <form action="{{ route('item.delete', $read->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-info" href="{{ route('item.show', $read->id) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a class="btn btn-sm btn-warning" href="{{ route('item.edit', $read->id) }}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button class="btn btn-sm btn-danger" onclick="return confirm('Yakin menghapus data ?')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>

    {{-- Tambah Data --}}
    {{-- Modal --}}

    <div class="modal fade" id="create-student">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Tambah Data</h4>
                </div>
                <form action="simpan_kategori" method="post" enctype="multipart/form-data">

                    @csrf
                    <div class="modal-body">
                        <label for="">Nama :</label>
                        <input type="text" class="form-control" name="name">
                        <hr>
                        

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save </button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    {{-- Tambah Data --}}
@endsection
@push('js')
    <script>
        $(function () {
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
    @endpush

resources/views/kontak.blade.php
@extends('template')

@section('content')

resources/views/suplier.blade.php
@extends('admin.layouts.app')
@section('content-header')

    Data Siswa <br> <br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#create-student">
        <i class="fa fa-plus"></i> Tambah Suplier
    </button>
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#create-student">
            <i class="fa fa-plus"></i> Import Data Barang
        </button>
@endsection
@section('header-small')

@endsection
@section('content')
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Data Barang</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Nama Toko</th>
                        <th>Nama Pemilik</th>
                        <th>Alamat</th>
                        <th>Nomor HP</th>
                        <th>Status</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($data as $read)
                    <tr>
                        <td>{{$read->nama_toko}}</td>
                        <td>{{$read->nama_pemilik}}</td>
                        <td>{{$read->alamat}}</td>
                        <td>{{$read->nomor_hp}}</td>
                        <td>{{$read->status}}</td>
                        <td>
                            <form action="{{ route('item.delete', $read->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-info" href="{{ route('item.show', $read->id) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a class="btn btn-sm btn-warning" href="{{ route('item.edit', $read->id) }}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button class="btn btn-sm btn-danger" onclick="return confirm('Yakin menghapus data ?')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>

    {{-- Tambah Data --}}
    {{-- Modal --}}

    <div class="modal fade" id="create-student">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Tambah Data</h4>
                </div>
                <form action="simpan_suplier" method="post" enctype="multipart/form-data">

                    @csrf
                    <div class="modal-body">
                        <label for="">Nama Toko :</label>
                        <input type="text" class="form-control" name="nama_toko">
                        <label for="">Nama Pemilik :</label>
                        <input type="text" name="nama_pemilik" class="form-control">
                        <label for="">Alamat :</label>
                        <input type="text" name="alamat" class="form-control">
                        <label for="">Nomor hp</label>
                        <input type="text" name="nomor_hp" class="form-control">
                        <label for="">Status</label>
                        <input type="text" name="status" class="form-control">
                        <hr>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save </button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    {{-- Tambah Data --}}
@endsection
@push('js')
    <script>
        $(function () {
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
    @endpush

resources/views/tambah_barang.blade.php
@extends('template')

@section('content')
<!DOCTYPE html>
<html>
<head>
	<title>Tambah Barang</title>
</head>
<body>
<form class="form-group" action="/post" method="post" enctype="multipart/form-data">
  @csrf
  <div class="container">
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Nama Barang</label>
      <input type="text" name="nama" class="form-control">
    </div>
    <div class="form-group col-md-6">
      <label for="inputEmail5">Stok Barang</label>
      <input type="text" name="jumlah" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Harga</label>
    <input type="text" name="harga" class="form-control" >
  </div>
  <div class="form-group">
    <label for="inputAddress2">Kategori Barang</label>
   <select name="kategori_id" class="form-control" id="list" onchange="myFunction()">
      @foreach($tampilan as $datanyobak)
      <option value="" hidden>~ PILIH KATEGORI ~</option>
          <option value="{{$datanyobak->id}}">{{$datanyobak->nama_kategori}}</option>
          @endforeach
    </select>
  </div>
  <div class="form-group">
    <label for="inputAddress2">Suplier ID</label>
    <input type="text" name="suplier_id" class="form-control" >
  </div>
  <div class="form-group">
    <input type="file" name="foto" class="file" id="validatedCustomFile">
    </div>
  
  </div>
</div>
    <button type="submit" class="btn btn-primary">Save</button><br>
  
</form>
</body>
</html>

<script>
function myFunction(){
      var list = document.getElementById("list");
      document.getElementById("kategori").value = list.options[list.selectedIndex].getAttribute('id_kategori');
      // document.getElementById("qty").value = list.options[list.selectedIndex].getAttribut('data-qty');
    }
</script>

@endsection

resources/views/transaksi.blade.php
@extends('template')

@section('content')
<header class="main-header">
        <!-- Start Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light navbar-default bootsnav" style="background-color: #fffa78">
            <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                    <a class="navbar-brand" href="index.html"><img src="image/smeas11.png" class="logo" alt="" width="190"></a>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">
                        <li class="nav-item"><a class="nav-link" href="../">Beranda</a></li>

                        <li class="dropdown megamenu-fw">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Kategori</a>
                            <ul class="dropdown-menu megamenu-content" role="menu">
                                <li>
                                    <div class="row">
                                        <div class="col-menu col-md-3">
                                            <h6 class="title">Atribut</h6>
                                            <div class="content">
                                                <ul class="menu-col">
                                                    <li><a href=Bat Jurusan></a></li>
                                                    <li><a href="../website/badge_jurusan">Badge Jurusan</a></li>
                                                    <li><a href="../website/dasi">Dasi</a></li>
                                                    <li><a href="../website/kaos_kaki">Kaos Kaki</a></li>
                                                    <li><a href="../website/topi">Topi</a></li>
                                                    <li><a href="../website/atribut_pramuka">Atribut Pramuka</a></li>
                                                    <li><a href="../website/sepatu">Sepatu</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- end col-3 -->
                                        <div class="col-menu col-md-3">
                                            <h6 class="title">Alat Tulis</h6>
                                            <div class="content">
                                                <ul class="menu-col">
                                                    <li><a href="#">Pensil</a></li>
                                                    <li><a href="#">Penghapus</a></li>
                                                    <li><a href="#">Bolpoin</a></li>
                                                    <li><a href="#">Penggaris</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- end col-3 -->
                                        <div class="col-menu col-md-3">
                                            <h6 class="title">Makanan Ringan</h6>
                                            <div class="content">
                                                <ul class="menu-col">
                                                    <li><a href="shop.html">Bidaran</a></li>
                                                    <li><a href="shop.html">Makaroni</a></li>
                                                    <li><a href="shop.html">Krupuk</a></li>
                                                    <li><a href="shop.html"></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="col-menu col-md-3">
                                            <h6 class="title">Accessories</h6>
                                            <div class="content">
                                                <ul class="menu-col">
                                                    <li><a href="shop.html">Bags</a></li>
                                                    <li><a href="shop.html">Sunglasses</a></li>
                                                    <li><a href="shop.html">Fragrances</a></li>
                                                    <li><a href="shop.html">Wallets</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- end col-3 -->
                                    </div>
                                    <!-- end row -->
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="../about">Tentang Kami</a></li>
                    </ul>
                </div>
    </header>