routes/web.php
<?php

// Route::get('/', function () {
//     return view('index');
// });
route::get('/','testController@home');
route::get('about','testController@about');

Route::group(['namespace'=>'Admin'],function (){
    Route::get('auth/login','AuthController@showLoginForm')->name('auth.showloginform');
    Route::post('/','AuthController@login')->name('login');
    Route::get('logout','AuthController@logout')->name('logout');
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'is_admin',
    'prefix'        => 'dashboard'
],function (){
    Route::name('dash.')->group(function (){
        Route::get('','DashboardController@index')->name('index');
    });
});

Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'is_admin',
'prefix'        => 'item'
],function (){
    Route::name('item.')->group(function (){
        Route::get('','ItemController@index')->name('index');
        Route::get('{id}','ItemController@show')->name('show');
        Route::post('','ItemController@store')->name('store');
        Route::get('edit/{id}','ItemController@edit')->name('edit');
        Route::put('{id}','ItemController@update')->name('update');
        Route::delete('{id}','ItemController@delete')->name('delete');
        Route::post('item/import_excel', 'ItemController@import_excel');
    });
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'supplier'
],function (){
    Route::name('supplier.')->group(function (){
        Route::get('','SupplierController@index')->name('index');
        Route::post('','SupplierController@store')->name('store');
        Route::get('edit/{id}','SupplierController@edit')->name('edit');
        Route::put('{id}','SupplierController@update')->name('update');
        Route::delete('{id}','SupplierController@destroy')->name('delete');
    });
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'category'
],function (){
    Route::name('category.')->group(function (){
        Route::get('','CategoryItemController@index')->name('index');
        Route::post('','CategoryItemController@store')->name('store');
        Route::get('edit/{id}','CategoryItemController@edit')->name('edit');
        Route::put('{id}','CategoryItemController@update')->name('update');
        Route::delete('category.delete/{id}','CategoryItemController@delete')->name('delete');
    });
});

Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'admin'
],function (){
    Route::name('admin.')->group(function (){
        Route::get('','AdminController@index')->name('index');
        Route::post('','AdminController@store')->name('store');
        Route::get('edit/{id}','AdminController@edit')->name('edit');
        Route::put('{id}','AdminController@update')->name('update');
        Route::delete('category.delete/{id}','AdminController@delete')->name('delete');
    });
});


Route::get('beranda', function () {
    return view('index');
});
Route::get('transaksi', function () {
    return view('transaksi');
});


Route::get('website/{id}', 'Admin\BarangController@tampil')->name('kategori.show');
// Route::get('website/dasi', 'Admin\BarangController@tampil');
//
Route::get('website/kaos_kaki', 'Admin\BarangController@tampil_kaoskaki');

Route::get('website/topi', 'Admin\BarangController@tampil_topi');

Route::get('website/atribut_pramuka', 'Admin\BarangController@tampil_atributperamuka');

Route::get('website/sepatu', 'Admin\BarangController@tampil_sepatu');

Route::get('website/badge_jurusan', 'Admin\BarangController@tampil_badge');

Route::get('website/status', function () {
    return view('website/status');
});

// Route::get('/dashboard', 'DashboardController@index');

resources/views/admin/app/admin/edit.blade.php
@extends('admin.layouts.app')
@section('content-header')
@endsection
@section('header-small')
@endsection
@section('content')
<div class="col-xs-12">
        <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Edit Form</h3>
                </div>
                <form action="{{route('admin.update',$data->id)}}" method="POST">
                    @method('put')
                    @csrf
                  <div class="box-body">
                    <div class="form-group">
                      <label for="">Nama Admin</label>
                      <input type="text" name="name" class="form-control" id="" placeholder="Masukkan Nama ADmin" value="{{$data->name}}">
                    </div>
                    <div class="form-group">
                        <label for="">Username Admin</label>
                        <input type="text" name="username" class="form-control" id="" placeholder="Masukkan Username Admin" value="{{$data->username}}">
                      </div>
                      <div class="form-group">
                        <label for="">Email Admin</label>
                        <input type="text" name="email" class="form-control" id="" placeholder="Masukkan Email Admin" value="{{$data->email}}">
                      </div>
                      <div class="form-group">
                        <label for="">Password Admin</label>
                        <input type="text" name="new_pass" class="form-control" id="" placeholder="Masukkan Password baru apabila ingin merubah">
                        <input type="hidden" name="password" class="form-control" id="" placeholder="Masukkan Password baru apabila ingin merubah" value="{{$data->password}}">
                      </div>
                  </div>


                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>
              </div>
</div>
@endsection

resources/views/admin/app/admin/index.blade.php
@extends('admin.layouts.app')
@section('content-header')

    Data Admin <br> <br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#create-student">
        <i class="fa fa-plus"></i> Tambah admin
    </button>
@endsection
@section('header-small')

@endsection
@section('content')
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Data admin</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($data as $read)
                    <tr>
                        <td>{{$read->name}}</td>
                        <td>
                            <form action="{{ route('admin.delete', $read->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-warning" href="{{ route('admin.edit', $read->id) }}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button class="btn btn-sm btn-danger" onclick="return confirm('Yakin menghapus data ?')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>

    {{-- Tambah Data --}}
    {{-- Modal --}}

    <div class="modal fade" id="create-student">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Tambah admin</h4>
                </div>
                <form action="{{route('admin.store')}}" method="post" enctype="multipart/form-data">

                    @csrf
                    <div class="modal-body">
                        <label for="">Nama :</label>
                        <input type="text" class="form-control" name="name">

                        <label for="">email :</label>
                        <input type="email" class="form-control" name="email">

                        <label for="">username :</label>
                        <input type="text" class="form-control" name="username">

                        <label for="">password :</label>
                        <input type="password" class="form-control" name="password">
                        <hr>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save </button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    {{-- Tambah Data --}}
@endsection
@push('js')
    <script>
        $(function () {
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
    @endpush