routes/web.php
<?php

// Route::get('/', function () {
//     return view('index');
// });
route::get('/','testController@home');
route::get('about','testController@about');

Route::group(['namespace'=>'Admin'],function (){
    Route::get('auth/login','AuthController@showLoginForm')->name('auth.showloginform');
    Route::post('/','AuthController@login')->name('login');
    Route::get('logout','AuthController@logout')->name('logout');
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'is_admin',
    'prefix'        => 'dashboard'
],function (){
    Route::name('dash.')->group(function (){
        Route::get('','DashboardController@index')->name('index');
    });
});

Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'is_admin',
'prefix'        => 'item'
],function (){
    Route::name('item.')->group(function (){
        Route::get('','ItemController@index')->name('index');
        Route::get('{id}','ItemController@show')->name('show');
        Route::post('','ItemController@store')->name('store');
        Route::get('edit/{id}','ItemController@edit')->name('edit');
        Route::put('{id}','ItemController@update')->name('update');
        Route::delete('{id}','ItemController@delete')->name('delete');
        Route::post('item/import_excel', 'ItemController@import_excel');
    });
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'supplier'
],function (){
    Route::name('supplier.')->group(function (){
        Route::get('','SupplierController@index')->name('index');
        Route::post('','SupplierController@store')->name('store');
        Route::get('edit/{id}','SupplierController@edit')->name('edit');
        Route::put('{id}','SupplierController@update')->name('update');
        Route::delete('{id}','SupplierController@destroy')->name('delete');
    });
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'category'
],function (){
    Route::name('category.')->group(function (){
        Route::get('','CategoryItemController@index')->name('index');
        Route::post('','CategoryItemController@store')->name('store');
        Route::get('edit/{id}','CategoryItemController@edit')->name('edit');
        Route::put('{id}','CategoryItemController@update')->name('update');
        Route::delete('category.delete/{id}','CategoryItemController@delete')->name('delete');
    });
});

Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'admin'
],function (){
    Route::name('admin.')->group(function (){
        Route::get('','AdminController@index')->name('index');
        Route::post('','AdminController@store')->name('store');
        Route::get('edit/{id}','AdminController@edit')->name('edit');
        Route::put('{id}','AdminController@update')->name('update');
        Route::delete('category.delete/{id}','AdminController@delete')->name('delete');
    });
});


Route::get('beranda', function () {
    return view('index');
});
Route::get('transaksi', function () {
    return view('transaksi');
});


Route::get('website/{id}', 'Admin\BarangController@tampil')->name('kategori.show');
// Route::get('website/dasi', 'Admin\BarangController@tampil');
//
Route::get('website/kaos_kaki', 'Admin\BarangController@tampil_kaoskaki');

Route::get('website/topi', 'Admin\BarangController@tampil_topi');

Route::get('website/atribut_pramuka', 'Admin\BarangController@tampil_atributperamuka');

Route::get('website/sepatu', 'Admin\BarangController@tampil_sepatu');

Route::get('website/badge_jurusan', 'Admin\BarangController@tampil_badge');

Route::get('website/status', function () {
    return view('website/status');
});

// Route::get('/dashboard', 'DashboardController@index');

resources/views/admin/layouts/components/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 0.1
    </div>
    <div class="footer-copyright">
        <p class="footer-company">All Rights Reserved. &copy; 2019 <a href="#">SMEAS.Koperasi</p>
    </div>
</footer>

resources/views/admin/layouts/components/navbar.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>S</b>KI</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>SMEAS. </b>Koperasi</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {{-- <!-- Messages: style can be found in dropdown.less-->
                <!-- User Account: style can be found in dropdown.less --> --}}
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{asset('dist/img/avatar04.png')}}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{Auth::user()->name}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{asset('dist/img/avatar04.png')}}" class="img-circle" alt="User Image">
                            <p>
                                {{ Auth::user()->name }}
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profil</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{route('logout')}}" class="btn btn-default btn-flat">Keluar</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/components/sidebar.blade.php
<aside class="main-sidebar">
    {{-- <!-- sidebar: style can be found in sidebar.less --> --}}
    <section class="sidebar">
        {{-- <!-- Sidebar user panel --> --}}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{asset('dist/img/avatar04.png')}}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{Auth::user()->name}}</p>
                <i class="fa fa-circle text-success"></i> Online
                </a>
            </div>
        </div>


        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">Inputan Barang</li>
            <li class=""><a href="{{route('dash.index')}}"><i class="fa fa-book"></i> <span>Transaksi</span></a></li>


            <li class="treeview">
                <a href="#"><i class="fa fa-book"></i>
                    <span>Barang</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('item.index') }}"><i class="fa fa-circle-o"></i> List Barang</a></li>
                    <li><a href="{{route('category.index')}}"><i class="fa fa-circle-o"></i>Kategori Barang</a></li>
                </ul>
            </li>

            <li class=""><a href="{{route('supplier.index')}}"><i class="fa fa-book"></i> <span>Suplier</span></a></li>
            <li class=""><a href="{{route('admin.index')}}"><i class="fa fa-book"></i> <span>Admin</span></a></li>
            <li class=""><a href=""><i class="fa fa-key"></i> <span>Status</span></a></li>








        </ul>
    </section>
    {{-- <!-- /.sidebar --> --}}
</aside>