routes/web.php
<?php

// Route::get('/', function () {
//     return view('index');
// });
route::get('/','testController@home');
route::get('about','testController@about');

Route::group(['namespace'=>'Admin'],function (){
    Route::get('auth/login','AuthController@showLoginForm')->name('auth.showloginform');
    Route::post('/','AuthController@login')->name('login');
    Route::get('logout','AuthController@logout')->name('logout');
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'is_admin',
    'prefix'        => 'dashboard'
],function (){
    Route::name('dash.')->group(function (){
        Route::get('','DashboardController@index')->name('index');
    });
});

Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'is_admin',
'prefix'        => 'item'
],function (){
    Route::name('item.')->group(function (){
        Route::get('','ItemController@index')->name('index');
        Route::get('{id}','ItemController@show')->name('show');
        Route::post('','ItemController@store')->name('store');
        Route::get('edit/{id}','ItemController@edit')->name('edit');
        Route::put('{id}','ItemController@update')->name('update');
        Route::delete('{id}','ItemController@delete')->name('delete');
        Route::post('item/import_excel', 'ItemController@import_excel');
    });
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'supplier'
],function (){
    Route::name('supplier.')->group(function (){
        Route::get('','SupplierController@index')->name('index');
        Route::post('','SupplierController@store')->name('store');
        Route::get('edit/{id}','SupplierController@edit')->name('edit');
        Route::put('{id}','SupplierController@update')->name('update');
        Route::delete('{id}','SupplierController@destroy')->name('delete');
    });
});


Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'category'
],function (){
    Route::name('category.')->group(function (){
        Route::get('','CategoryItemController@index')->name('index');
        Route::post('','CategoryItemController@store')->name('store');
        Route::get('edit/{id}','CategoryItemController@edit')->name('edit');
        Route::put('{id}','CategoryItemController@update')->name('update');
        Route::delete('category.delete/{id}','CategoryItemController@delete')->name('delete');
    });
});

Route::group([
    'namespace'     => 'Admin',
    'middleware'    => 'auth',
    'prefix'        => 'admin'
],function (){
    Route::name('admin.')->group(function (){
        Route::get('','AdminController@index')->name('index');
        Route::post('','AdminController@store')->name('store');
        Route::get('edit/{id}','AdminController@edit')->name('edit');
        Route::put('{id}','AdminController@update')->name('update');
        Route::delete('category.delete/{id}','AdminController@delete')->name('delete');
    });
});


Route::get('beranda', function () {
    return view('index');
});
Route::get('transaksi', function () {
    return view('transaksi');
});


Route::get('website/{id}', 'Admin\BarangController@tampil')->name('kategori.show');
// Route::get('website/dasi', 'Admin\BarangController@tampil');
//
Route::get('website/kaos_kaki', 'Admin\BarangController@tampil_kaoskaki');

Route::get('website/topi', 'Admin\BarangController@tampil_topi');

Route::get('website/atribut_pramuka', 'Admin\BarangController@tampil_atributperamuka');

Route::get('website/sepatu', 'Admin\BarangController@tampil_sepatu');

Route::get('website/badge_jurusan', 'Admin\BarangController@tampil_badge');

Route::get('website/status', function () {
    return view('website/status');
});

// Route::get('/dashboard', 'DashboardController@index');

app/Http/Controllers/Admin/ItemController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\CategoryItem;
use App\Entities\Item;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Entities\Suplier;
use Alert;
use App\Imports\BarangImport;
use Maatwebsite\Excel\Facades\Excel;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        view()->share(
            [
                'data'=> Item::all(),
                'category'=>CategoryItem::all(),
                'suplier'=>Suplier::all()
            ]
        );
        return view('admin.app.item.index');
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['image' => 'required']);
       $foto = $request->file('image');
       $nama_file = time()."_".$foto->getClientOriginalName();
       $tujuan_upload = 'data_file';
       $foto->move($tujuan_upload,$nama_file);
        $n = new Item();
        $n->name = $request->name;
        $n->price = $request->price;
        $n->stock = $request->stock;
        $n->image = $nama_file;
        $n->category_id = $request->category_id;
        $n->suplier_id = $request->suplier_id;
        $n->save();
        return redirect()->back();
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $id)
    {
        view()->share([
            'data'=>$id
        ]);
        return view('admin.app.item.edit');
    }

    /**
     * Update the specified resource in storage.
     *'name','price','stock','image'
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Item $id)
    {
        if($request->hasFile('image')){
            $request->validate(['image' => 'required']);
            $foto = $request->file('image');
            $nama_file = time()."_".$foto->getClientOriginalName();
            $tujuan_upload = 'data_file';
            $foto->move($tujuan_upload,$nama_file);
            $id->update([
                'name'=>$request->name,
                'price'=>$request->price,
                'stock'=>$request->stock,
                'image'=>$nama_file,
            ]);
            return redirect()->route('item.index');
        }
        else{
            $id->update([
                'name'=>$request->name,
                'price'=>$request->price,
                'stock'=>$request->stock,
            ]);
            return redirect()->route('item.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(Item $id)
    {
        $id->delete();
        return redirect()->back();
    }

    public function import_excel(Request $request) 
  {
    // validasi
    $this->validate($request, [
      'file' => 'required|mimes:csv,xls,xlsx'
    ]);
 
    // menangkap file excel
    $file = $request->file('file');
 
    // membuat nama file unik
    $nama_file = rand().$file->getClientOriginalName();
 
    // upload ke folder file_siswa di dalam folder public
    $file->move('file_barang',$nama_file);
 
    // import data
    Excel::import(new BarangImport, public_path('/file_barang/'.$nama_file));
 
    // notifikasi dengan session
    Session::flash('sukses','Data Siswa Berhasil Diimport!');
 
    // alihkan halaman kembali
    return redirect('/item');
  }
}

resources/views/admin/app/item/edit.blade.php
@extends('admin.layouts.app')
@section('content-header')
@endsection
@section('header-small')
@endsection
@section('content')
<div class="col-xs-12">
        <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Edit Form</h3>
                </div>
                <form action="{{route('item.update',$data->id)}}" method="POST" enctype="multipart/form-data">
                    @method('put')
                    @csrf
                  <div class="box-body">
                    <div class="form-group">
                      <label for="">Nama Barang</label>
                      <input type="text" name="name" class="form-control"  value="{{$data->name}}">
                    </div>
                    <div class="form-group">
                            <label for="">Harga Barang</label>
                            <input type="text" name="price" class="form-control"  value="{{$data->price}}">
                    </div>
                    <div class="form-group">
                        <label for="">Stok Barang</label>
                         <input type="text" name="stock" class="form-control"  value="{{$data->stock}}">
                    </div>
                    <div class="form-group">
                        <label for="">Gambar Barang</label>
                        <img src="{{asset('data_file/'.$data->image)}}" alt="" style="width: 50px;height: 50px">
                        <input type="file" name="image">
                    </div>
                  </div>
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>
              </div>
</div>
@endsection

resources/views/admin/app/item/index.blade.php
@extends('admin.layouts.app')
@section('content-header')
<link rel="shortcut icon" href="image/favicon.ico">
    Data Siswa <br> <br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#create-student">
        <i class="fa fa-plus"></i> Tambah Barang Jualan
    </button>
    <button type="button" class="btn btn-primary mr-5" data-toggle="modal" data-target="#importExcel">
            IMPORT EXCEL
        </button>
@endsection
@section('header-small')

@endsection
@section('content')

{{-- notifikasi form validasi --}}
        @if ($errors->has('file'))
        <span class="invalid-feedback" role="alert">
            <strong>{{ $errors->first('file') }}</strong>
        </span>
        @endif
 
        {{-- notifikasi sukses --}}
        @if ($sukses = Session::get('sukses'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button> 
            <strong>{{ $sukses }}</strong>
        </div>
        @endif
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Data Barang</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Kategori</th>
                        <th>Harga</th>
                        <th>Stok</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($data as $read)
                    <tr>
                        <td>{{$read->name}}</td>
                        <td>{{$read->category['name']}}</td>
                        <td>{{$read->price}}</td>
                        <td>{{$read->stock}}</td>
                        <td>
                            <form action="{{ route('item.delete', $read->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-warning" href="{{ route('item.edit', $read->id) }}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button class="btn btn-sm btn-danger" onclick="return confirm('Yakin menghapus data ?')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>

    {{-- Tambah Data --}}
    {{-- Modal --}}

    <div class="modal fade" id="create-student">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Tambah Data</h4>
                </div>
                <form action="{{route('item.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <label for="">Nama :</label>
                        <input type="text" class="form-control" name="name">
                        <label for="">Harga :</label>
                        <input type="text" name="price" class="form-control">
                        <label for="">Stok :</label>
                        <input type="text" name="stock" class="form-control">
                        
                        <label for="">Category</label>
                        <!-- <input type="text" name="category_id" class="form-control"> -->
                        <select class="form-control" name="category_id">
                            <option></option>
                            @foreach($category as $data)
                            <option value="{{$data->id}}">{{$data->name}}</option>
                            @endforeach
                        </select>
                        <label for="">Suplier</label>
                        <select class="form-control" name="suplier_id">
                            <option></option>
                            @foreach($suplier as $data)
                            <option value="{{$data->id}}">{{$data->nama_toko}}</option>
                            @endforeach
                        </select>
                        <hr>
                        <label for="">Gambar</label>
                        <input type="file" name="image" class="form-control">



                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save </button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    
 
        <!-- Import Excel -->
        <div class="modal fade" id="importExcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <form method="post" action="item/import_excel" enctype="multipart/form-data">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Import Excel</h5>
                        </div>
                        <div class="modal-body">
 
                            {{ csrf_field() }}
                            
 
                            <label>Pilih file excel</label>
                            <div class="form-group">
                                <input type="file" name="file" required="required">
                            </div>
 
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Import</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {{-- Tambah Data --}}
@endsection
@push('js')
    <script>
        $(function () {
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
    @endpush